// <auto-generated />
namespace PocketBuilds.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class renamed_date_entry_and_added_date_to_notes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamed_date_entry_and_added_date_to_notes));
        
        string IMigrationMetadata.Id
        {
            get { return "201401311220359_renamed_date_entry_and_added_date_to_notes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
