// <auto-generated />
namespace PocketBuilds.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class removed_date_related_fields_on_models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_date_related_fields_on_models));
        
        string IMigrationMetadata.Id
        {
            get { return "201401311122099_removed_date_related_fields_on_models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
