// <auto-generated />
namespace PocketBuilds.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class readded_date_with_annotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(readded_date_with_annotations));
        
        string IMigrationMetadata.Id
        {
            get { return "201401311211373_readded_date_with_annotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
