// <auto-generated />
namespace PocketBuilds.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class added_date_related_fields_to_BuildOrder_and_Note : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_date_related_fields_to_BuildOrder_and_Note));
        
        string IMigrationMetadata.Id
        {
            get { return "201401310949391_added_date_related_fields_to_BuildOrder_and_Note"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
